### ISSUE TITLE
[Enhancement]:  Please upgrade to Obs-studio 28.0

### ISSUE THREAD

**Issue by C138** [snapcrafters/obs-studio#165] opened 2022-09-29 16:59 UTC
### What changes would you like?

https://github.com/obsproject/obs-studio/releases/tag/28.0.0

**Comment by jor1196** [comment] 2022-12-08 04:53
I already asked for this in the snap forum but apparently we see that flatpak wins again

**Comment by popey** [comment] 2023-10-11 11:55
Duplicate of #168

**Closed by popey** 2023-10-11 11:55 UTC
Labels: enhancement
