### ISSUE TITLE
Obs shutting off at start

### ISSUE THREAD

**Issue by rkleczek457** [snapcrafters/obs-studio#126] opened 2021-07-05 10:40 UTC
Im using Ubuntu 21.04 and when i press the obs icon to open it,it will appear for half a second and then dissapear. No crash codes or anything like that,it just crashes.Only time it works is the first time after an install.

**Comment by q-wertz** [comment] 2021-07-07 18:50
Duplicate of https://github.com/snapcrafters/obs-studio/issues/124

**Closed** 2021-08-05 15:05 UTC
