### ISSUE TITLE
[Enhancement]: OBS 1.28 + WebSockets 5.0

### ISSUE THREAD

**Issue by jaw-sh** [snapcrafters/obs-studio#163] opened 2022-08-13 18:56 UTC
### What changes would you like?

OBS has released version 1.28 which now packages WebSockets version 5.0 by default. WS5 uses a completely different API than version 4. I would love to see this snap updated.

**Comment by popey** [comment] 2023-10-11 11:55
Duplicate of #168

**Closed by popey** 2023-10-11 11:55 UTC
Labels: enhancement
