### ISSUE TITLE
UI does not use the correct scaling

### ISSUE THREAD

**Issue by yerbestpal** [snapcrafters/obs-studio#56] opened 2020-07-04 18:53 UTC
This is on a fresh install. I think it is font scaling that is causing the problem.

![Screenshot from 2020-07-04 19-52-08](https://user-images.githubusercontent.com/15250241/86519141-ddac0500-be2f-11ea-8cc5-81097adf98ef.png)

**Comment by yerbestpal** [comment] 2020-07-04 18:55
Applying the Rachni or Acri themes uses a font which is too small.

![Screenshot from 2020-07-04 19-55-01](https://user-images.githubusercontent.com/15250241/86519181-44c9b980-be30-11ea-83c0-837c40240646.png)

**Comment by flexiondotorg** [comment] 2020-11-08 13:58
Closing this bug due to no feedback and not being able to reproduce the issue.

**Closed by flexiondotorg** 2020-11-08 13:58 UTC
Labels: help wanted
