### ISSUE TITLE
Can not open OBS-Studio after install in rhel 8.2

### ISSUE THREAD

**Issue by abornn** [snapcrafters/obs-studio#76] opened 2020-08-27 22:28 UTC
obs-studio
Qt: Session management error: None of the authentication protocols specified are supported
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
info: CPU Speed: 2457.270MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 7717MB Total, 180MB Free
info: Kernel Version: Linux 4.18.0-193.14.3.el8_2.x86_64
info: Distribution: "Ubuntu Core" "18"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.6
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) UHD Graphics 620 (KBL GT2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.8, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.3.0-ee225959
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.3.0-ee225959
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.1.0)
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vnc.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: No scene file found, creating default scene
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 11.1-rebootstrapped'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 11.1-rebootstrapped'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1f.3.analog-stereo'
info: Switched to scene 'Scene'
warning: Failed to glob scene collections
Segmentation fault (core dumped)

I did the installation via snap
following this link:  https://snapcraft.io/install/obs-studio/rhel

**Comment by rpodcast** [comment] 2020-08-28 00:17
Just wanted to add that the same thing happened to me on a fresh install of the snap and running Pop OS 20.04 (newly acquired Thelio Desktop).  Session output in case it helps:

```
eric@system76-pc:~$ obs-studio 
Qt: Session management error: None of the authentication protocols specified are supported
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
info: CPU Speed: 1698.348MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 32034MB Total, 26422MB Free
info: Kernel Version: Linux 5.4.0-7642-generic
info: Distribution: Missing /etc/os-release !
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.8-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation GeForce RTX 2060 SUPER/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 440.100, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.8.3.0-ee225959
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
info: [StreamFX] Loaded Version 0.8.3.0-ee225959
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libUIOHook: Cross-platfrom userland keyboard and mouse hooking.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/libuiohook/

libUIOHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

libUIOHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [obs-browser]: Version 2.8.6
info: NVENC supported
info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.1.0)
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'replay-source.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     scrab.so
info:     rtmp-services.so
info:     replay-source.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vnc.so
info:     obs-vintage-filter.so
info:     obs-transitions.so
info:     obs-transition-matrix.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     move-transition.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     input-overlay.so
info:     image-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory

info: ==== Startup complete ===============================================
error: Service '' not found
info: No scene file found, creating default scene
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.usb-Logitech_Logitech_Wireless_Headset_88C626875C5F-00.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
info: pulse-input: Started recording from 'alsa_input.usb-Logitech_Logitech_Wireless_Headset_88C626875C5F-00.mono-fallback'
info: Switched to scene 'Scene'
warning: Failed to glob scene collections
Segmentation fault (core dumped)
```

**Comment by flexiondotorg** [comment] 2020-08-28 10:53
Duplicate of #71

**Closed by flexiondotorg** 2020-08-28 10:53 UTC
