### ISSUE TITLE
200% cpu Usage with no scenes or sources

### ISSUE THREAD

**Issue by likwidoxigen** [snapcrafters/obs-studio#75] opened 2020-08-27 14:56 UTC
Snap is still unusable on Xubuntu 20.04.
Tested both latest/stable 25.0.8  and latest/edge 25.0.8 and the new August 22 build as well.
Scene with zero sources and default audio in mixer and it's using 2 full cores (190%+ cpu). 
Prior to this update usage was 30% when not streaming and 70% when streaming with multiple overlays etc.

Happy to troubleshoot or provide more information, please let me know.

APT package at 25.0.3 behaves as expected.
[2020-07-04 16-13-54.txt](https://github.com/snapcrafters/obs-studio/files/4873801/2020-07-04.16-13-54.txt)

This is a re-submit of #57 which was closed as a duplicate but was not truly a duplicate. 7

**Comment by flexiondotorg** [comment] 2020-08-28 10:49
Duplicate of #72

**Closed by flexiondotorg** 2020-08-28 10:49 UTC

**Comment by flexiondotorg** [comment] 2020-08-28 16:47
Fixed via https://github.com/snapcrafters/obs-studio/commit/2fa8a2fe331973ead41730f616416424d28e1818
