### ISSUE TITLE
Browse button no longer works, image, media, etc.

### ISSUE THREAD

**Issue by jefferoonie** [snapcrafters/obs-studio#135] opened 2021-09-18 03:50 UTC
Running OBS 27.0.0 on Xubuntu 20.10. (Now 21.04 and problem persists) 

It has been working great for the little bit I use it for. Just recently, I can no longer browse to an image file, media file, or anything when adding a source. The button no longer does anything. Has anyone seen this?

![2021-07-14_22-06](https://user-images.githubusercontent.com/23159722/133871611-2560e400-7dae-4285-bb31-3a58e2bd31dd.png)

Thanks,
Jeff

**Comment by ali1234** [comment] 2021-09-18 09:31
This is fixed in 27.1.0-rc1

Duplicate of https://github.com/snapcrafters/obs-studio/issues/134

**Comment by jefferoonie** [comment] 2021-09-28 22:31
Sorry that I didn't see this, and thank you for pointing it out. I just installed 27.1.0-rc1, and I seem to have the same problem.

**Comment by naufalfachrian** [comment] 2021-10-05 02:52
Not fixed in OBS 27.1.0-rc1 for me.

**Comment by flexiondotorg** [comment] 2021-10-12 02:24
I can reproduce this using Xubuntu 21.04. If you install `xdg-desktop-portal-gtk` the file dialogues will work correctly. All the Ubuntu flavours ship an appropriate xdg-desktop-portal implementation, except for Xubuntu.

```bash
apt install xdg-desktop-portal-gtk
```

**Closed by flexiondotorg** 2021-10-12 02:24 UTC

**Comment by FernandoKGA** [comment] 2022-01-23 16:14
Is this still fixed? I'm having issues with it at 27.1.3.

**Comment by jefferoonie** [comment] 2022-01-25 14:45
> Is this still fixed? I'm having issues with it at 27.1.3.

It started working for me, starting with release 27.1.3.

**Comment by FernandoKGA** [comment] 2022-01-25 14:54
> > Is this still fixed? I'm having issues with it at 27.1.3.
> 
> It started working for me, starting with release 27.1.3.

It's not working for me, maybe it's an edge case or just some OS bug. I will download the source and try to make the bug reproducible to provide further information.
