### ISSUE TITLE
OBS not running?

### ISSUE THREAD

**Issue by FluffyFluffy200** [snapcrafters/obs-studio#80] opened 2020-09-07 20:41 UTC
Hi, I'm new to Linux and such, I have Linux; Debian Buster. The terminal says this when I do `snap run obs-studio`
2020/09/07 15:30:06.789198 cmd_run.go:880: WARNING: cannot start document portal: dbus: connection closed by user
snap run obs-studio
Found /root/snap/obs-studio/1124/.config/obs-studio/basic/scenes/Untitled.json
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.

so I did untitled.json thing, then did `snap run obs-studio` again
it said this
```
2020/09/07 15:30:06.789198 cmd_run.go:880: WARNING: cannot start document portal: dbus: connection closed by user
snap run obs-studio
Found /root/snap/obs-studio/1124/.config/obs-studio/basic/scenes/Untitled.json
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
root@penguin:/home/yanderegirl101sfanmail# snap run obs-studio
2020/09/07 15:30:41.977572 cmd_run.go:880: WARNING: cannot start document portal: read unix @->/run/user/1000/bus: EOF
Found /root/snap/obs-studio/1124/.config/obs-studio/basic/scenes/Untitled.json
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
root@penguin:/home/yanderegirl101sfanmail# 2020/09/07 15:30:06.789198 cmd_run.go:880: WARNING: cannot start document portal: dbus: connection closed by user
bash: 2020/09/07: No such file or directory
root@penguin:/home/yanderegirl101sfanmail# snap run obs-studio
2020/09/07 15:36:55.810608 cmd_run.go:880: WARNING: cannot start document portal: read unix @->/run/user/1000/bus: EOF
Found /root/snap/obs-studio/1124/.config/obs-studio/basic/scenes/Untitled.json
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
root@penguin:/home/yanderegirl101sfanmail# Found /root/snap/obs-studio/1124/.config/obs-studio/basic/scenes/Untitled.json
bash: Found: command not found
root@penguin:/home/yanderegirl101sfanmail# No protocol specified
bash: No: command not found
root@penguin:/home/yanderegirl101sfanmail# qt.qpa.screen: QXcbConnection: Could not connect to display :0
bash: qt.qpa.screen:: command not found
root@penguin:/home/yanderegirl101sfanmail# Could not connect to any X display.
```

**Comment by FluffyFluffy200** [comment] 2020-09-07 21:57
I'll post a video soon

**Comment by FluffyFluffy200** [comment] 2020-09-07 22:01
https://youtu.be/G0f_jb0vefw

says this the second time I tried it once I stopped recording
```
Found /home/yanderegirl101sfanmail/snap/obs-studio/1124/.config/obs-studio/basic/scenes/Untitled.json
Using Wayland-EGL
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: 06/7a
info: CPU Speed: 1094.400MHz
info: Physical Cores: 2, Logical Cores: 2
info: Physical Memory: 2779MB Total, 123MB Free
info: Kernel Version: Linux 5.4.40-04224-g891a6cce2d44
info: Distribution: "Ubuntu Core" "18"
No protocol specified
info: Unable to open X display
No protocol specified
info: Freeing OBS context data
Segmentation fault (core dumped)
```

**Comment by popey** [comment] 2020-09-08 09:27
I don't believe OBS is well supported under Wayland right now. If you use an X11 session, it'll likely work fine. Sorry about that.

**Comment by flexiondotorg** [comment] 2020-09-08 18:21
This looks like a duplicate of #50

**Closed by flexiondotorg** 2020-09-08 18:21 UTC
