### ISSUE TITLE
Opens and shuts off immediately (Ubuntu 20.04)

### ISSUE THREAD

**Issue by kormic** [snapcrafters/obs-studio#125] opened 2021-06-30 09:00 UTC
Hey everyone,  when I start obs it informs me about a new version of the Advances Scene Switcher and if I should backup the old settings. Either I press No or Yes it opens and shuts down immediately. I am running Ubuntu 20.04 using Wayland and OBS is at version 27

This is the dialog
![image](https://user-images.githubusercontent.com/10133190/123932937-98ff6f00-d99a-11eb-91ad-d86bd5d8d144.png)

this is the ouput:
`
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread

(process:21817): Gtk-WARNING **: 12:04:04.537: Locale not supported by C library.
	Using the fallback 'C' locale.
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: User enabled --multi flag and is now running multiple instances of OBS.
info: Command Line Arguments: --multi
info: Platform: Wayland
info: CPU Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
info: CPU Speed: 3343.135MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 15692MB Total, 6431MB Free
info: Kernel Version: Linux 5.4.0-74-generic
info: Distribution: "Ubuntu Core" "20"
info: Session Type: wayland
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.0.0-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.5
info: Loading up OpenGL on adapter X.Org Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-74-generic, LLVM 11.0.0)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.2.6, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   2560x1440
	output resolution: 1920x1080
	downscale filter:  Lanczos
	fps:               60/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
info: [StreamFX] Loading Version 0.10.0.0-g5888c7d2
info: [StreamFX] Loaded Version 0.10.0.0-g5888c7d2
info: [adv-ss] version: 2ce0b35921be892c987c7dbb5fc90db38f15f0a6
info: [adv-ss] trying '/home/komic'
info: [adv-ss] trying '/usr/lib'
info: [adv-ss] trying '/usr/local/lib'
info: [adv-ss] trying '/usr/lib/x86_64-linux-gnu'
info: [adv-ss] trying '/usr/local/opt/curl/lib'
warning: [adv-ss] can't find the curl library
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
info: [Freeze Filter] loaded version 0.3.2
info: [Gradient Source] loaded version 0.1.0
info: [pango]: Loaded system fontconfig
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: [linux-vkcapture] plugin loaded successfully (version 0.5)
info: [Move Transition] loaded version 2.4.1
error: Unable to load NvFCB library
warning: Failed to initialize module 'nvfbc.so'
warning: Failed to load 'en-US' text for module: 'obs-audio-pan-filter.so'
info: [obs-audio-pan-filter] plugin loaded successfully (version 0.1.0)
info: [obs-browser]: Version 2.14.3
info: [obs-browser]: CEF Version 87.1.14+ga29e9a3+chromium-87.0.4280.141
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

info: FFMPEG VAAPI supported
warning: Failed to load 'en-US' text for module: 'obs-gphoto.so'
info: obs-gstreamer build: 2b6aa8d
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.4'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
warning: Failed to load 'en-US' text for module: 'obs-vnc.so'
info: [obs-vnc] plugin loaded successfully (version 0.3.1)
info: [obs-websocket] you can haz websockets (version 4.9.0)
info: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.2
info: [obs-websocket] module loaded!
info: [Replay Source] loaded version 1.6.8
info: [Source Copy] loaded version 0.1.1
info: [Source Record] loaded version 0.1.4
info: [Source Switcher] loaded version 0.3.0
info: [spectralizer] Loading v1.3.2 build time 2021.06.01 21:48
info: [TimeWarpScan] loaded version 0.1.6
info: [Transition Table] loaded version 0.2.0
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     transition-table.so
info:     time-warp-scan.so
info:     text-freetype2.so
info:     spectralizer.so
info:     source-switcher.so
info:     source-record.so
info:     source-copy.so
info:     sndio.so
info:     rtmp-services.so
info:     replay-source.so
info:     recursion-effect.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-vnc.so
info:     obs-transitions.so
info:     obs-rtspserver.so
info:     obs-rgb-levels-filter.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-gstreamer.so
info:     obs-gphoto.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     obs-audio-pan-filter.so
info:     nvfbc.so
info:     move-transition.so
info:     linux-vkcapture.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     libtext-pango.so
info:     image-source.so
info:     gradient-source.so
info:     frontend-tools.so
info:     freeze-filter.so
info:     dynamic-delay.so
info:     dvd-screensaver.so
info:     downstream-keyer.so
info:     dir-watch-media.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info:     advanced-scene-switcher.so
info:     StreamFX.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: pulse-am: Prevented feedback-loop in 'default'
info: [Loaded global audio device]: 'Desktop Audio'
info:     - monitoring: monitor and output
info: pulse-input: Server name: 'pulseaudio 13.99.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: source 'Mic/Aux' enabled push-to-mute
info: [Loaded global audio device]: 'Mic/Aux'
info:     - filter: 'Noise Gate' (noise_gate_filter)
info:     - filter: 'Gain' (gain_filter)
info:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
info: v4l2-input: Start capture from /dev/v4l/by-path/pci-0000:00:14.0-usb-0:5:1.0-video-index0
error: v4l2-input: Unable to open device
error: v4l2-input: Initialization failed
error: Source ID 'droidcam_obs' not found
error: Failed to create source 'DroidCam OBS'!
error: Source ID 'xshm_input' not found
error: Failed to create source 'Screen Capture (XSHM)'!
info: Switched to scene 'Scene'
info: adding 64 milliseconds of audio buffering, total audio buffering is now 64 milliseconds (source: Mic/Aux)

info: [adv-ss] trying to reconnect to  in 10 seconds.
info: ------------------------------------------------
info: [adv-ss] started
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Mic/Aux' (pulse_input_capture)
info:         - filter: 'Noise Gate' (noise_gate_filter)
info:         - filter: 'Gain' (gain_filter)
info:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
info:     - source: 'Screen Capture (XSHM)' (xshm_input)
info:     - source: 'DroidCam OBS' (droidcam_obs)
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: ------------------------------------------------
info: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] io thread started
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  13
  Current serial number in output stream:  13
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
info: [obs-websocket] server stopped successfully
[2021-06-30 12:04:09] [info] asio handle_accept error: asio.system:125 (Operation aborted.)
[2021-06-30 12:04:09] [info] Error getting remote endpoint: asio.system:9 (Bad file descriptor)
[2021-06-30 12:04:09] [fail] WebSocket Connection Unknown - "" - 0 asio.system:125 Operation aborted.
Segmentation fault (core dumped)
`

**Comment by q-wertz** [comment] 2021-07-07 18:50
Duplicate of https://github.com/snapcrafters/obs-studio/issues/124

**Closed** 2021-08-05 15:05 UTC
