### ISSUE TITLE
File requesters don't work anywhere in the program or plugins

### ISSUE THREAD

**Issue by ali1234** [snapcrafters/obs-studio#134] opened 2021-09-03 16:12 UTC
To reproduce:

1. Start OBS
2. Make a new scene
3. Add an Image source
4. In the properties, click "Browse" on the "Image File" option

Expected result:

A file requester should appear allowing you to select an image.

Actual result:

Nothing happens when you click the button.

This problem exists anywhere that a file requester should be shown, for example these plugins:

- Text (Freetype 2)
- Image
- Media source

It also seems to affect OBS itself, for example in the main menu click Tools->Scripts and then click the "+".

This may be because I am running a self-built snap using `snapcraft try`?

**Comment by flexiondotorg** [comment] 2021-09-08 12:05
I can not reproduce this issue.

What revision of the OBS snap are you using and what distro and desktop environment are you using?

**Comment by ali1234** [comment] 2021-09-08 12:56
Ubuntu 20.04, Xfce desktop, and the snap version from my PR #131.

**Comment by ymauray** [comment] 2021-09-09 21:43
I have the same problem with the stable version (27.0.1)
```
$ uname -a
Linux heimdall 5.11.0-31-lowlatency #33-Ubuntu SMP PREEMPT Wed Aug 11 14:21:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ymauray** [comment] 2021-09-09 21:45
The funny thing is, it worked fine last week.

**Comment by ymauray** [comment] 2021-09-09 22:31
This seems to be fixed in 27.1.0-rc1

**Closed** 2021-09-15 00:11 UTC
Labels: question

**Comment by ali1234** [comment] 2021-09-18 09:30
Fixed in 27.1.0-rc1 for me too.

**Comment by jefferoonie** [comment] 2021-09-20 02:56
Thanks for the update.  Looks like I will have to obtain this outside of the snap store.

**Comment by jefferoonie** [comment] 2021-09-20 03:10
Sorry that I didn't see this, and thank you for pointing it out.  I just installed 27.1.0-rc1, and I seem to have the same problem.
