### ISSUE TITLE
Decklink Mini Monitor not recognized

### ISSUE THREAD

**Issue by gre2gor** [snapcrafters/obs-studio#137] opened 2021-10-06 11:19 UTC
Hi,
with snap installation of obs-studio I finnaly managed to get SRT working as an Media source, but can not output to Decklink Mini Monitor. It reports that drivers are not installed. 
I have second installation of obs-studio installed trough Ubuntu software where Decklink works, but I have no SRT IN.
So for now I run snapcrafters obs-studio as SRT grab then I forward this as NDI source for "normal" obs-studio. 
I have tried everything, with fresh install of Ubuntu and just snapcrafters obs-studio and Decklink drivers. But it behaves the same. 
Is it possible to get Decklink Mini Monitor working inside snapcrafters obs-studio? That would be aswesome.

I get "Output ID 'decklink_output' not found
Failed to create output 'decklink_output'

And in the first lines of Log: "A Decklink iterator could not be created. The Deklink drivers may not be installed"

Best regards and thank you for all your efforts.
Grega

**Comment by flexiondotorg** [comment] 2021-10-12 01:47
Duplicate of #40

**Closed by flexiondotorg** 2021-10-12 01:47 UTC
