### ISSUE TITLE
FIX IT ITS GIVING ME ERROR ITS STILL UNDER DEVELOPMENT OBS STUDIO IN SNAP STORE CONTINUE DEVELOPING IT

### ISSUE THREAD

**Issue by JeanMichael10** [snapcrafters/obs-studio#127] opened 2021-08-04 04:43 UTC
FIX IT RIGHT NOW WE DONT WAIT AFTER MILLION YEARS TO BE FIXED OKAY FIX IT QUICKEST AS U CAN AND CONTINUE DEVELOPING IT!

**Comment by Lin-Buo-Ren** [comment] 2021-08-04 04:55
Please provide the specific error message text and the specific snap revision you're reproducing this issue.

**Comment by FuckWindowsandLinux** [comment] 2021-08-04 05:38
U KNOW WHAT IT IS, ITS NOT NECESSARY TO ASK, HERE WHAT IT SAYS ''Unable to
install woe-usb: status-code=409 kind-snap-change-conflict message=snap
''obs studio'' has ''install-snap'' change in progress like this error
message exactly!

**Comment by FuckWindowsandLinux** [comment] 2021-08-04 05:42
https://drive.google.com/file/d/1HmXqIrQ0dDFxUxuPHIugfrGOVwe0CsD3/view?usp=sharing

**Comment by FuckWindowsandLinux** [comment] 2021-08-04 05:43
Open the link, the screenshot of it is provided!

**Comment by FuckWindowsandLinux** [comment] 2021-08-04 05:45
Also, after it install in edge classic mode this how it opened ur software its in complete i cant record i cant do anything continue please that why im request it! https://drive.google.com/file/d/148GX8Oe3EJYg2v0LVWK_9zPQiAdB8LpI/view?usp=sharing

**Comment by Lin-Buo-Ren** [comment] 2021-08-04 05:54
> U KNOW WHAT IT IS, ITS NOT NECESSARY TO ASK

Just for the record, I did have no idea what problem you're experiencing, but thanks for cooperating!

> message=snap ''obs studio'' has ''install-snap'' change in progress

The error message indicates that snapd, the service that manages snaps, is busy installing the obs studio snap and cannot process your request right now.

You may try to abort the process by first running the `snap changes` command in a terminal, locate the ID of the change that is problematic, then run `snap abort __change_id__` to try to abort the change.

Reboot the system may also be helpful, just in case snapd is stuck in a state for whatever reason.

If you still can reproduce the problem, consider posting a thread in the [Snapcraft forum](https://forum.snapcraft.io)(under the `snapd` topic category, if the problem is rather snapd-specific rather than the snap itself).

> Unable to install woe-usb: status-code=409 kind-snap-change-conflict 

As I happened to be the WoeUSB project's maintainer, I would urge you to follow the instructions at <https://github.com/WoeUSB/WoeUSB#run-from-source> instead, WoeUSB doesn't currently maintain an official snap package and the third-party distribution in the Snap Store is highly outdated.

**Comment by JeanMichael10** [comment] 2021-08-04 12:16
Yh thanks, for @ss if they come back fk them fk windows and fk microsoft!
:)

**Comment by JeanMichael10** [comment] 2021-08-04 12:17
@Lin-Buo-Ren Lin-Buo-RenAlso, After it install in edge classic mode this how it opened ur software its in complete i cant record i cant do anything continue please that why im request it! https://drive.google.com/file/d/148GX8Oe3EJYg2v0LVWK_9zPQiAdB8LpI/view?usp=sharing

**Comment by flexiondotorg** [comment] 2021-08-05 14:59
Closing this because this is not citing a bug in the snap.

**Closed by flexiondotorg** 2021-08-05 14:59 UTC
Labels: bug, question

**Comment by JeanMichael10** [comment] 2021-08-06 07:12
Yh thanks! ;)
