### ISSUE TITLE
Custom browser unable to perform Google services sign-in

### ISSUE THREAD

**Issue by rpodcast** [snapcrafters/obs-studio#100] opened 2020-12-31 04:06 UTC
Originally mentioned in this twitter [thread](https://twitter.com/robinjuste/status/1344324461806424064), myself and at least one other user have not been able to log in to various Google services (such as YouTube Studio) within a custom browser dock.  Unfortunately I am still seeing the problem even after the fix in da74ac8febaf957b05b6b90908a3cba096f3eaa8 .  Currently running the snap version 1186 on both my Ubuntu 20.04 and Pop OS 20.04 workstations.

![image](https://user-images.githubusercontent.com/1043111/103393943-88596380-4af3-11eb-9966-03d10440fc77.png)

**Comment by flexiondotorg** [comment] 2021-02-13 18:33
I can't reproduce this issue.

**Comment by rpodcast** [comment] 2021-02-16 02:35
I just tried it on my installation and I'm still seeing the same issue.  I'm on version 1195 of the snap (I believe that is the latest version).  Any troubleshooting diagnostics I can give you?  I tried launching the snap from a terminal to see if any diagnostic messages would be printed, but no new messages are added when the failed sign in occurs.

**Comment by flexiondotorg** [comment] 2021-02-16 05:22
Can you backup `~/snap/obs-studio`, then remove that directory and start the `obs-studio` snap with a clean configuration. The try adding a single browser dock.

**Comment by rpodcast** [comment] 2021-02-18 03:49
Unfortunately still the same error with the clean configuration.

**Comment by flexiondotorg** [comment] 2021-02-19 13:30
I simply can not reproduce this issue. That said, I've uploaded a new revision (1198) of the snap (26.1.2-197-g81a89e689) to the edge channel, which has a slightly newer CEF build included. Please test it and report back.

**Comment by flexiondotorg** [comment] 2021-02-22 10:37
@rpodcast Does connection the `password-manager-service` interface help?

    snap connect obs-studio:password-manager-service

**Comment by flexiondotorg** [comment] 2021-03-25 07:51
Closing this due to no feedback and that I am unable to reproduce the issue with OBS Studio in the edge channel. As documented in the README, OBS snap may require the `process-control` and `password-manager-service` interfaces to be connected.

    snap connect obs-studio:process-control
    snap connect obs-studio:password-manager-service

**Closed by flexiondotorg** 2021-03-25 07:51 UTC
Labels: question

**Comment by rpodcast** [comment] 2021-03-25 16:16
FWIW I ran the above connects and still get the same error.  Unless others can reproduce this besides me I am fine with keeping it closed until we can get better diagnostics.
