### ISSUE TITLE
v4l2loopback devices not showing in Ubuntu 20.04

### ISSUE THREAD

**Issue by KnutssonDevelopment** [snapcrafters/obs-studio#108] opened 2021-02-07 14:02 UTC
Output stream from gphoto2 is not selectable in OBS-Studio from snap. Regular OBS Studio works fine.

**Comment by flexiondotorg** [comment] 2021-02-14 10:54
Duplicate of #102

**Closed by flexiondotorg** 2021-02-14 10:54 UTC

**Comment by KnutssonDevelopment** [comment] 2021-02-16 16:45
> Duplicate of #102

No it is NOT a duplicate. It is not the same issue. #102 is about not seeing a preview. This one is about the gPhoto2 plugin not being is OBS at all. You are NOT able to add the gPhoto2 as a source. It is NOT there.

Please reopen this bug.
