### ISSUE TITLE
Preview no longer working, video black

### ISSUE THREAD

**Issue by stijnghesquiere** [snapcrafters/obs-studio#90] opened 2020-11-10 14:09 UTC
Since the November 8th update, the preview does no longer work in OBS. It stays black and tend to lock OBS. 

If add a video device, it shows in the device settings (properties for 'Video Capture Device (V4L2)'). But once I change anything, the video goes black. 

In the main OBS screen, I cannot turn on 'Enable Preview'. It doesn't gave an error, actually nothing happens if I try to turn on preview. 

Even if I select an image instead of a video source, it stays black. No preview. 

If I change window arrangements in OBS (like make the preview panel smaller), it also messes things up. 

Ubuntu 20.04, Radeon RX580 GPU. 
Video works in other applications, not in OBS. 
V4L2sink also doesn't work anymore for Zoom, Skype and Teams (virtual device not showing up). I can get it to work with Discord however. 

Edit: added info regarding V4Lsink

**Comment by stijnghesquiere** [comment] 2020-11-10 16:16
Is it possible for the maintainers to provide an older version in stable and put the new features in edge? 
That would help a lot, as I always dread updates to obs as it a work in progress and it have caused issues before... 
I tried to revert the snap, but alas to no avail. 
Many thanks!

**Comment by stijnghesquiere** [comment] 2020-11-10 21:14
Under wayland I do get a preview, so it looks like a combination of Xorg, RX580 GPU and some change in code.

**Comment by asonix** [comment] 2020-12-11 21:37
I'd like to add that I experience this issue on elementary OS 5.1 (based on Ubuntu 18.04 with hwe) on an Nvidia GTX 1070 with the snap, but installing the obs deb from the official PPA works fine.

**Comment by flexiondotorg** [comment] 2020-12-27 11:39
Are you referring to just the preview of camera sources being black or the preview of the entire scene being black?

**Comment by asonix** [comment] 2020-12-27 14:24
The entire preview window, where it shows the current scene

**Comment by asonix** [comment] 2020-12-27 15:51
Here's what I see in OBS, complete with artifacting when I resize the lower bar

![image](https://user-images.githubusercontent.com/5304643/103174571-e9014b80-4828-11eb-840f-84e2824bef92.png)
![image](https://user-images.githubusercontent.com/5304643/103174581-fb7b8500-4828-11eb-9977-3fcb759e44d6.png)

**Comment by stijnghesquiere** [comment] 2020-12-27 22:20
The basic preview stays black, but the windowed projector (preview) option works and gives a preview in a separate window.

**Comment by flexiondotorg** [comment] 2020-12-29 17:29
Please attach a log file from your current session so I can review it.

**Comment by asonix** [comment] 2020-12-29 22:12
Here's stdout and stderr from opening obs, resizing the bar, and closing obs

[err.log](https://github.com/snapcrafters/obs-studio/files/5752364/err.log)
[out.log](https://github.com/snapcrafters/obs-studio/files/5752365/out.log)

**Comment by flexiondotorg** [comment] 2020-12-30 10:31
I don't really know what to suggest other than perhaps trying the 455 NVIDIA drivers:

  * https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by asonix** [comment] 2020-12-30 15:38
It turns out I had already added that PPA and installed the 450 driver. I tried upgrading to 455 and I'm having the same issue. I wonder if removing the PPA and downgrading the driver would work. Although I'm not convinced that's it since the OP is having the same issue with an AMD card

fwiw I also confirmed that the windowed projector works, as mentioned in @stijnghesquiere 's comment

**Comment by flexiondotorg** [comment] 2023-10-11 12:22
Fixed via #172

**Closed by flexiondotorg** 2023-10-11 12:22 UTC
Labels: question
